# CMake generated Testfile for 
# Source directory: /home/packages/mysql-5.5.27
# Build directory: /home/packages/mysql-5.5.27
# 
# This file replicates the SUBDIRS() and ADD_TEST() commands from the source
# tree CMakeLists.txt file, skipping any SUBDIRS() or ADD_TEST() commands
# that are excluded by CMake control structures, i.e. IF() commands.
SUBDIRS(zlib)
SUBDIRS(cmd-line-utils/libedit)
SUBDIRS(storage/heap)
SUBDIRS(storage/csv)
SUBDIRS(storage/myisammrg)
SUBDIRS(storage/federated)
SUBDIRS(storage/blackhole)
SUBDIRS(storage/perfschema)
SUBDIRS(storage/example)
SUBDIRS(storage/innobase)
SUBDIRS(storage/myisam)
SUBDIRS(storage/archive)
SUBDIRS(plugin/semisync)
SUBDIRS(plugin/fulltext)
SUBDIRS(plugin/auth)
SUBDIRS(plugin/audit_null)
SUBDIRS(plugin/daemon_example)
SUBDIRS(include)
SUBDIRS(dbug)
SUBDIRS(strings)
SUBDIRS(vio)
SUBDIRS(regex)
SUBDIRS(mysys)
SUBDIRS(libmysql)
SUBDIRS(unittest/mytap)
SUBDIRS(unittest/mysys)
SUBDIRS(extra)
SUBDIRS(tests)
SUBDIRS(client)
SUBDIRS(sql)
SUBDIRS(sql/share)
SUBDIRS(libservices)
SUBDIRS(mysql-test)
SUBDIRS(mysql-test/lib/My/SafeProcess)
SUBDIRS(support-files)
SUBDIRS(scripts)
SUBDIRS(sql-bench)
SUBDIRS(man)
SUBDIRS(packaging/WiX)
